# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aWMZMxsPHj6qYB0WrMqD3v37KIA_1C7R
"""

import math

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Error: division by zero"
    else:
        return a / b

def power(a, b):
    return a ** b

def square_root(a):
    if a < 0:
        return "Error: square root of a negative number"
    else:
        return math.sqrt(a)

print("Scientific Calculator")

while True:
    print("\nPlease select operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")
    print("5. Power")
    print("6. Square root")
    print("7. Quit")

    choice = input("Enter choice (1-7): ")

    if choice == '7':
        break

    if choice in ('1', '2', '3', '4', '5', '6'):
        if choice == '1':
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
            print(num1, "+", num2, "=", add(num1, num2))

        elif choice == '2':
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
            print(num1, "-", num2, "=", subtract(num1, num2))

        elif choice == '3':
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
            print(num1, "*", num2, "=", multiply(num1, num2))

        elif choice == '4':
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
            print(num1, "/", num2, "=", divide(num1, num2))

        elif choice == '5':
            num1 = float(input("Enter base number: "))
            num2 = float(input("Enter exponent: "))
            print(num1, "^", num2, "=", power(num1, num2))

        elif choice == '6':
            num = float(input("Enter a number: "))
            print("Square root of", num, "=", square_root(num))

    else:
        print("Invalid input")